# 通用的mybatis数据源配置
spring:
  datasource:
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接url
    url: jdbc:mysql://193.112.178.249:3306/acmbak
    # 数据库用户名
    username: weedien
    # 数据库密码
    password: 031209

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml